version: '3.8'

services:
  audio-splitter:
    build: .
    image: audio-splitter-service:0.0.1
    container_name: audio-splitter
    ports:
      - "8002:8002"
    volumes:
      - ./shared_storage:/shared_storage
    privileged: true
    restart: unless-stopped
